title: Low's website
description: Misc
avatar: "/assets/img/avatar.jpg"
round-avatar: true
author: boa
navbar-links:
  About Me: "aboutme"
Author's home: "https://lowcraft.org"

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"